### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by anpoit00** [caadxyz/glfwOcctViewer#2]
Hello, I tried to compile your sample code and i received 
make
Scanning dependencies of target glfwocct

> 

[ 25%] Building CXX object CMakeFiles/glfwocct.dir/GlfwOcctView.cpp.o
In file included from /home/mabi/Documents/glfwOcctViewer/GlfwOcctView.h:25,
                 from /home/mabi/Documents/glfwOcctViewer/GlfwOcctView.cpp:22:
/home/mabi/Documents/glfwOcctViewer/GlfwOcctWindow.h:68:31: error: 'virtual Aspect_TypeOfResize GlfwOcctWindow::DoResize() const' marked 'override', but does not override
   virtual Aspect_TypeOfResize DoResize() const Standard_OVERRIDE;
                               ^~~~~~~~
/home/mabi/Documents/glfwOcctViewer/GlfwOcctView.cpp: In member function 'void GlfwOcctView::initWindow(int, int, const char*)':
/home/mabi/Documents/glfwOcctViewer/GlfwOcctView.cpp:112:67: error: invalid new-expression of abstract class type 'GlfwOcctWindow'
   myOcctWindow = new GlfwOcctWindow (theWidth, theHeight, theTitle);
                                                                   ^
In file included from /home/mabi/Documents/glfwOcctViewer/GlfwOcctView.h:25,
                 from /home/mabi/Documents/glfwOcctViewer/GlfwOcctView.cpp:22:
/home/mabi/Documents/glfwOcctViewer/GlfwOcctWindow.h:34:7: note:   because the following virtual functions are pure within 'GlfwOcctWindow':
 class GlfwOcctWindow : public Aspect_Window
       ^~~~~~~~~~~~~~
In file included from /home/mabi/Documents/glfwOcctViewer/GlfwOcctWindow.h:27,
                 from /home/mabi/Documents/glfwOcctViewer/GlfwOcctView.h:25,
                 from /home/mabi/Documents/glfwOcctViewer/GlfwOcctView.cpp:22:
/home/mabi/Occt_Builds/occt7-5-shared-debug/include/opencascade/Aspect_Window.hxx:61:47: note: 	'virtual Aspect_TypeOfResize Aspect_Window::DoResize()'
   Standard_EXPORT virtual Aspect_TypeOfResize DoResize() = 0;
                                               ^~~~~~~~
make[2]: *** [CMakeFiles/glfwocct.dir/build.make:63: CMakeFiles/glfwocct.dir/GlfwOcctView.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/glfwocct.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`
Do you have any idea ?
OCCT 7.5

**Comment by mahaidong** [comment]
updated to 7.5.0
